### ISSUE TITLE
Etherscan Cannot Find totalSupply method

### ISSUE THREAD

**Issue by mineo333** [Serenity-Financial/smart-contract#1]
Why can't etherscan find the totalSupply method. This is a great problem because us investors are looking for a way to track the burning of tokens. Unless we have this number I will not be able to get  good outlook for when I will get my money back. Please get this fixed ASAP.

**Comment by mineo333** [comment]
Update on this issue. The ERC20.sol code shows: 
` function totalSupply() public view returns (uint256) { totalSupply; }`
and then
` uint256 public totalSupply = 0;`
However, it doesn't reassign itself or point to something. This therefore returns 0 on etherscan.

**Comment by V-Alexeev** [comment]
Hi @mineo333!

Unfortunately even if we fix it in code, it won't change in the smart contract, since it's already deployed. It's impossible to change a deployed smart contract.

So we have to live with this error.

Probably we should provide a total supply tracker at our website, that's a good idea.
